spring:
  application:
    name: rest-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salesApp?useTimezone=true&serverTimezone=UTC
    username: root
    password: 81050050
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernete:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
logging:
  level:
    root: INFO #projeto completo.

    com.myProject: DEBUG  # Pacote raiz do PROJETO!

    # Logs do Spring Web (para ver resolução de exceções e endpoints)
    org.springframework.web: DEBUG

    # Reduce ruído de outros módulos
    org.hibernate: ERROR
    org.springframework.transaction: ERROR
springdoc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true