
cors:
  originPattern: http://localhost:8080,http://localhost:3000,https://www.linkedin.com/in/marciocleydev
file:
  upload-dir: /intellij/API_file_dir/upload
spring:
  application:
    name: rest-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salesApp?useTimezone=true&serverTimezone=UTC
    username: root
    password: 81050050
  jpa:
    hibernate:
      ddl-auto: none #depois das migrations

    properties:
      hibernete:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    root: INFO #projeto completo.

    com.myProject: DEBUG  # Pacote raiz do PROJETO!

    # Logs do Spring Web (para ver resolução de exceções e endpoints)
    org.springframework.web: DEBUG

    # Reduce ruído de outros módulos
    org.hibernate: ERROR
    org.springframework.transaction: ERROR
springdoc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true