insert into `tb_category`(name) values
 ('Food - Condiments'),
 ('Food - Oils'),
 ('Food - Frozen Foods'),
 ('Food - Frozen Foods'),
 ('Food - Snacks'),
 ('Food - Meat'),
 ('Kitchen'),
 ('Food - Frozen Meals'),
 ('Electronics'),
 ('Kitchen'),
 ('Outdoor'),
 ('Travel'),
 ('Kitchen'),
 ('Home'),
 ('Garden'),
 ('Food - Breakfast'),
 ('Food - Grains'),
 ('Clothing - Bottoms'),
 ('Audio'),
 ('Food - Produce'),
 ('Food - Frozen Foods'),
 ('Accessories'),
 ('Books'),
 ('Food - Canned Goods'),
 ('Food - Cereal'),
 ('Food - Dairy'),
 ('Food - Frozen Foods'),
 ('Beauty'),
 ('Food - Canned Goods'),
 ('Food - Frozen Vegetables'),
 ('Food - Frozen Foods'),
 ('Food - Meat'),
 ('Kitchen'),
 ('Home'),
 ('Fitness'),
 ('Health'),
 ('Food - Frozen Vegetables'),
 ('Food - Meat'),
 ('Food - Snacks'),
 ('Food - Beverages'),
 ('Kitchen'),
 ('Home'),
 ('Food - Baking Goods'),
 ('Food - Snacks'),
 ('Outdoor'),
 ('Electronics'),
 ('Food - Frozen Foods'),
 ('Clothing - Bottoms'),
 ('Kitchen'),
 ('Fitness');
