name: Continuous Integration and Delivery with Github Actions
on:
  push:
    branches:
      - "main"
      #caso queira fazer deploy em outra branch, basta alterar aqui
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Application .jar
        working-directory: ./ #indica o diretorio onde está o pom do projeto no github, nesse caso está na raiz do projeto
        run: ./mvnw clean package

      - name: Docker compose build
        working-directory: ./projetos/SpringSalesApp
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run:
          #cria tag com o id do github actions, para cada execução ter uma versão com o numero do job
          docker tag ${{ secrets.DOCKER_USERNAME }}/salesapp:latest ${{ secrets.DOCKER_USERNAME }}/salesapp:${{github.run_id}}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/salesapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/salesapp:${{github.run_id}} #variavel de ambiente do github actions
